// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audio/transcribe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Recebe arquivo de áudio e retorna texto transcrito via Whisper",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Transcreve áudio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Formato do áudio (wav, mp3, webm, flac, m4a). Se omitido, detectado pelo Content-Type",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.AudioTranscribeResponse"
                        }
                    },
                    "400": {
                        "description": "audio required / format required / api key not set",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing token / invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to transcribe speech",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/audio/tts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Recebe texto e retorna áudio MP3 sintetizado via Edge TTS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "audio/mpeg"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Sintetiza fala",
                "parameters": [
                    {
                        "description": "Texto a sintetizar",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.AudioTTSPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Áudio MP3",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "invalid payload / text required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing token / invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to synthesize speech",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Retorna status do servidor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "transport.AudioTTSPayload": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "transport.AudioTranscribeResponse": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.5",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lia Server API",
	Description:      "Server Backend da Lia",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
